apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mcp-calculator-server
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/cpu-throttling: 'false'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: '740202511174-compute@developer.gserviceaccount.com'
      containers:
      - image: us-central1-docker.pkg.dev/agentic-ai-batch-2025/mcp-server/calculator-server:latest
        ports:
        - name: http1
          containerPort: 8080
        resources:
          limits:
            cpu: '1000m'
            memory: 512Mi
        startupProbe:
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
  traffic:
  - percent: 100
    latestRevision: true
